### ISSUE TITLE
Move to ffmpeg

### ISSUE THREAD

**Issue by lu-zero** [mozilla/rainbow#1]
FFmpeg should provide a better way to interleave media packets and has already some capture support that might get leveraged for this project. (not to mention support for rtsp)

**Comment by anantn** [comment]
We'd love to use ffmpeg!
- Is there a way to build ffmpeg with only a select number of codecs? We'd only need support for vp8, vorbis and theora in webm and ogg containers. This is to ensure our final binary redistributable is as small as possible, and also ensure we stay clear from other codecs that have an unknown patent landscape.
- Is the capture support cross-platform? Does it support DirectX on Windows and Quicktime on the Mac?

**Comment by lu-zero** [comment]
- ffmpeg is fully modular so you should be able to get just what you need and nothing more
- for windows I see that there is a vfw capture available, on the mac side we are probably lacking but porting the capture code isn't that hard.

On a second thought you might use a thinned libvlc (the captures are there already, the codecs will be provided by ffmpeg as well)

If you are serious about adoption we could check what's missing and which is the least impacting solution.

**Comment by anantn** [comment]
We discussed this for a bit and unfortunately it seems like we will not be able to use ffmpeg. The reason is that ffmpeg is licensed as LGPL which is incompatible with the MPL and we are required to tri-license all our code as MPL/LGPL/GPL.

We are continuing to work on our own capture & multiplexing code.

**Comment by lu-zero** [comment]
gtk+ and Qt aren't MPL and yet they are used...
Same could be said for gstreamer...
