### ISSUE TITLE
Camera to canvas, if possible, not camera or canvas.  

### ISSUE THREAD

**Issue by taboca** [mozilla/rainbow#12]
I think this may not be exactly rainbow totally.  But I think the discussion is key here.

I see that rainbow operates in two ways : camera or canvas capture. I wonder if I can use the canvas capture mode and yet get the access to the webcam. What I am interested in doing, use case, is to filter the camera bits, and perform some JS_based graphics operation to them, and then pass draw to the recording area. This would enable us, for example, to put a mini user camera next to a recording area, and also other things such as amazing graphics effects.

**Comment by taboca** [comment]
Here is an example of rainbow recording canvas and a webcam image being pasted into the canvas: 

http://dl.dropbox.com/u/20061784/rainbow-cam-canvas.ogv

However in this example, I am using a Flash to JavaScript-Canvas image to capture the webcam.

**Comment by anantn** [comment]
The default capture mode of Rainbow is in fact, recording to a canvas, which you can then manipulate as you please. Could you try manipulating the 'tehcanvas' object in the example (https://github.com/mozilla/rainbow/blob/master/content/example.html) while it is used to show the preview to see if you can obtain the desired effect?

**Comment by anantn** [comment]
If you wish the record the result of combining both the webcam and your changes to it, I would imagine you can start two rainbow instances, one that paints the camera preview to a canvas and another that records the content of your 'painted' canvas into a video. Does this not work?

**Comment by taboca** [comment]
I see, interesting workaround. One rainbow to get cam, other to record. That can work for now. Eventually a cam to canvas API would be cool too for Firefox.
