### ISSUE TITLE
window.navigator.service not being injected on Windows 7 in 0.4

### ISSUE THREAD

**Issue by dmose** [mozilla/rainbow#15]
The following error is in the error console, which I was surprised to see since this isn't Mac...

Error: Rainbow could not load component, are you in 32-bit mode?
Source File: chrome://rainbow/content/injector.js
Line: 84

**Comment by anantn** [comment]
Hmm, just tried on a fresh Firefox 4 profile and could not reproduce the issue. Does the component load if manually invoked via Cc["@labs.mozilla.com/media/recorder;1"].getService(Ci.IMediaRecorder); in the error console?

**Comment by dmose** [comment]
Error: Components.classes['@labs.mozilla.com/media/recorder;1'] is undefined
Source File: javascript:%20Components.classes["@
labs.mozilla.com/media/recorder;1
"].getService(Components.interfaces.IMediaRecorder);
Line: 1

**Comment by dmose** [comment]
That's from my existing profile; I'l try a fresh one momentarily.

**Comment by dmose** [comment]
Same problem in a fresh profile.  The build id is "Mozilla/5.0 (Windows NT 6.1; rv:2.0) Gecko/20100101 Firefox/4.0"
about:buildconfig looks like this:

about:buildconfig
Source

Built from http://hg.mozilla.org/releases/mozilla-2.0/rev/6be9e31d01b4
Build platform
target
i686-pc-mingw32
Build tools
Compiler    Version     Compiler flags
d;D:\mozilla-build\msys\mozilla-build\python25\python2.5.exe -O e;D:\mozilla-build\msys\builds\moz2_slave\rel-2.0-w32-bld\build\build\cl.py cl  14.00.50727.762     -TC -nologo -W3 -Gy -Fdgenerated.pdb -DNDEBUG -DTRIMMED -Zi -Zi -UDEBUG -DNDEBUG -GL -wd4624 -wd4952 -O1
d;D:\mozilla-build\msys\mozilla-build\python25\python2.5.exe -O e;D:\mozilla-build\msys\builds\moz2_slave\rel-2.0-w32-bld\build\build\cl.py cl  14.00.50727.762     -GR- -TP -nologo -Zc:wchar_t- -W3 -Gy -Fdgenerated.pdb -wd4800 -DNDEBUG -DTRIMMED -Zi -Zi -UDEBUG -DNDEBUG -GL -wd4624 -wd4952 -O1
Configure arguments

--enable-application=browser --enable-update-channel=release --enable-update-packaging --enable-jemalloc --enable-tests --enable-official-branding

**Comment by dmose** [comment]
This is Windows 7 Home Premium, running on Parallels Desktop 5.0.9376.  Looking at the System section of Control Panel -> System and Security -> System, this is a 32-bit version of Windows 7, and the processor is listed as "Intel(R) Core(TM) 2 Duo CPU  T9900 @ 3.06Ghz  3.06Ghz".

**Comment by anantn** [comment]
It turns out that libogg had a dependency on MSVCRT80.DLL which isn't present on machines that don't have VS2005 installed. Several solutions to the dll problem were suggested, but thankfully I was able to recompile all the xiph libraries to link statically to the C run-times in order to avoid dependencies on any DLL at all.

Commit https://github.com/mozilla/rainbow/commit/af3a4ef7298af026a8db47a88c3d250d36edc6ad should have fixed this. If it still doesn't work, re-open and we shall investigate further!

**Comment by anantn** [comment]
Forgot to mention that updated XPIs are both on AMO and http://proness.kix.in/misc/rainbow-0.4-dev.xpi
