### ISSUE TITLE
which sdk version do i need to compile with?

### ISSUE THREAD

**Issue by dunkfordyce** [mozilla/rainbow#19]
I tried with the xulrunner 7 sdk but i get the following:
  dunk@atitude:/data/dunk/projects/rainbow$ MOZSDKDIR=sdk/xulrunner-sdk make
  make -C components
  make[1]: Entering directory `/data/dunk/projects/rainbow/components'
 g++ -DRAINBOW_Nix -pipe -Os -shared -DMOZ_NO_MOZALLOC -DMOZILLA_STRICT_API -fshort-wchar -fPIC -fno-rtti -fno-exceptions -fno-strict-aliasing -fno-common -pthread -Wall -Werror -Wconversion -Wpointer-arith -Woverloaded-virtual -Wsynth -Wno-ctor-dtor-privacy -Wno-non-virtual-dtor -Wcast-align -Wno-long-long -include xpcom-config.h -I. -ILinux -Isdk/xulrunner-sdk/include -Isdk/xulrunner-sdk/include/system_wrappers -Isdk/xulrunner-sdk/include/xpcom -Isdk/xulrunner-sdk/include/string -Isdk/xulrunner-sdk/include/content -Isdk/xulrunner-sdk/include/dom -Isdk/xulrunner-sdk/include/nspr -Isdk/xulrunner-sdk/sdk/include -I../lib/Linux_x86-gcc3/include -o libmediarecorder.so MediaRecorder.cpp MediaModule.cpp Convert.cpp VideoSource.cpp Linux/VideoSourceNix.cpp AudioSource.cpp Linux/AudioSourceNix.cpp VideoSourceCanvas.cpp  -pthread -pipe -m32 -Wl,-z,defs -Wl,-rpath-link,sdk/xulrunner-sdk/bin sdk/xulrunner-sdk/lib/libxpcomglue_s.a -Lsdk/xulrunner-sdk/lib -Lsdk/xulrunner-sdk/bin -lxpcomglue_s -lxpcom -lnspr4 -lmozalloc -lplds4 -lplc4 -lrt -lasound ../lib/Linux_x86-gcc3/libvidcap.a ../lib/Linux_x86-gcc3/libvorbis.a ../lib/Linux_x86-gcc3/libvorbisenc.a ../lib/Linux_x86- gcc3/libogg.a ../lib/Linux_x86-gcc3/libtheora.a
 g++: sdk/xulrunner-sdk/lib/libxpcomglue_s.a: No such file or directory
 cc1plus: fatal error: xpcom-config.h: No such file or directory
 compilation terminated.
 cc1plus: fatal error: xpcom-config.h: No such file or directory
 compilation terminated.
 cc1plus: fatal error: xpcom-config.h: No such file or directory
 compilation terminated.
 cc1plus: fatal error: xpcom-config.h: No such file or directory
 compilation terminated.
 cc1plus: fatal error: xpcom-config.h: No such file or directory
 compilation terminated.
 cc1plus: fatal error: xpcom-config.h: No such file or directory
 compilation terminated.
 cc1plus: fatal error: xpcom-config.h: No such file or directory
 compilation terminated.
 cc1plus: fatal error: xpcom-config.h: No such file or directory
 compilation terminated. 
 make[1]: *** [libmediarecorder.so] Error 1 
 make[1]: Leaving directory`/data/dunk/projects/rainbow/components'
 make: **\* [components/libmediarecorder.so] Error 2

**Comment by dunkfordyce** [comment]
i found my last problem was due to not setting a full path to the xulrunner sdk. i now get a bit further but still its not compiling.  Im using ubuntu natty and gcc 4.5.2

dunk@atitude:~/projects/rainbow$ MOZSDKDIR=/home/dunk/projects/rainbow/sdk/xulrunner-sdk/ make
make -C components
make[1]: Entering directory `/data/dunk/projects/rainbow/components'
g++ -DRAINBOW_Nix -pipe -Os -shared -DMOZ_NO_MOZALLOC -DMOZILLA_STRICT_API -fshort-wchar -fPIC -fno-rtti -fno-exceptions -fno-strict-aliasing -fno-common -pthread -Wall -Werror -Wconversion -Wpointer-arith -Woverloaded-virtual -Wsynth -Wno-ctor-dtor-privacy -Wno-non-virtual-dtor -Wcast-align -Wno-long-long -include xpcom-config.h -I. -ILinux -I/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include -I/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/system_wrappers -I/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/xpcom -I/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/string -I/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/content -I/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/dom -I/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nspr -I/home/dunk/projects/rainbow/sdk/xulrunner-sdk//sdk/include -I../lib/Linux_x86-gcc3/include -o libmediarecorder.so MediaRecorder.cpp MediaModule.cpp Convert.cpp VideoSource.cpp Linux/VideoSourceNix.cpp AudioSource.cpp Linux/AudioSourceNix.cpp VideoSourceCanvas.cpp  -pthread -pipe -m32 -Wl,-z,defs -Wl,-rpath-link,/home/dunk/projects/rainbow/sdk/xulrunner-sdk//bin /home/dunk/projects/rainbow/sdk/xulrunner-sdk//lib/libxpcomglue_s.a -L/home/dunk/projects/rainbow/sdk/xulrunner-sdk//lib -L/home/dunk/projects/rainbow/sdk/xulrunner-sdk//bin -lxpcomglue_s -lxpcom -lnspr4 -lmozalloc -lplds4 -lplc4 -lrt -lasound ../lib/Linux_x86-gcc3/libvidcap.a ../lib/Linux_x86-gcc3/libvorbis.a ../lib/Linux_x86-gcc3/libvorbisenc.a ../lib/Linux_x86-gcc3/libogg.a ../lib/Linux_x86-gcc3/libtheora.a
MediaRecorder.cpp:693:1: error: pasting "u" and ""audio"" does not give a valid preprocessing token
MediaRecorder.cpp:695:1: error: pasting "u" and ""video"" does not give a valid preprocessing token
MediaRecorder.cpp:697:1: error: pasting "u" and ""width"" does not give a valid preprocessing token
MediaRecorder.cpp:699:1: error: pasting "u" and ""height"" does not give a valid preprocessing token
MediaRecorder.cpp:701:1: error: pasting "u" and ""channels"" does not give a valid preprocessing token
MediaRecorder.cpp:703:1: error: pasting "u" and ""rate"" does not give a valid preprocessing token
MediaRecorder.cpp:705:1: error: pasting "u" and ""quality"" does not give a valid preprocessing token
MediaRecorder.cpp:707:1: error: pasting "u" and ""source"" does not give a valid preprocessing token
In file included from MediaRecorder.h:61:0,
                 from MediaRecorder.cpp:37:
/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsStringAPI.h:1101:3: error: ‘char16_t’ was not declared in this scope
cc1plus: warnings being treated as errors
In file included from MediaRecorder.h:74:0,
                 from MediaRecorder.cpp:37:
./VideoSource.h:80:22: error: ‘virtual nsresult VideoSource::Start(nsIDOMCanvasRenderingContext2D*)’ was hidden
Linux/VideoSourceNix.h:53:14: error:   by ‘nsresult VideoSourceNix::Start(nsIOutputStream*, nsIDOMCanvasRenderingContext2D*)’
MediaRecorder.cpp: In member function ‘void MediaRecorder::ParseProperties(nsIPropertyBag2*)’:
MediaRecorder.cpp:693:34: error: ‘u’ was not declared in this scope
MediaRecorder.cpp:693:34: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:693:34: error: expected ‘)’ before string constant
MediaRecorder.cpp:693:34: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:693:34: error: expected ‘)’ before string constant
MediaRecorder.cpp:693:77: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:693:77: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:695:34: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:695:34: error: expected ‘)’ before string constant
MediaRecorder.cpp:695:34: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:695:34: error: expected ‘)’ before string constant
MediaRecorder.cpp:695:77: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:695:77: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:697:36: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:697:36: error: expected ‘)’ before string constant
MediaRecorder.cpp:697:36: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:697:36: error: expected ‘)’ before string constant
MediaRecorder.cpp:697:79: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:697:79: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:699:36: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:699:36: error: expected ‘)’ before string constant
MediaRecorder.cpp:699:36: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:699:36: error: expected ‘)’ before string constant
MediaRecorder.cpp:699:81: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:699:81: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:701:36: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:701:36: error: expected ‘)’ before string constant
MediaRecorder.cpp:701:36: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:701:36: error: expected ‘)’ before string constant
MediaRecorder.cpp:701:81: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:701:81: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:703:36: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:703:36: error: expected ‘)’ before string constant
MediaRecorder.cpp:703:36: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:703:36: error: expected ‘)’ before string constant
MediaRecorder.cpp:703:77: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:703:77: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:705:36: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:705:36: error: expected ‘)’ before string constant
MediaRecorder.cpp:705:36: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:705:36: error: expected ‘)’ before string constant
MediaRecorder.cpp:705:80: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:705:80: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:707:34: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:707:34: error: expected ‘)’ before string constant
MediaRecorder.cpp:707:34: error: expected primary-expression before ‘(’ token
MediaRecorder.cpp:707:34: error: expected ‘)’ before string constant
MediaRecorder.cpp:707:79: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp:707:79: error: expected ‘)’ before ‘;’ token
MediaRecorder.cpp: In static member function ‘static void MediaRecorder::BeginSessionThread(void*)’:
MediaRecorder.cpp:769:75: error: cannot allocate an object of abstract type ‘VideoSourceNix’
Linux/VideoSourceNix.h:47:43: note:   because the following virtual functions are pure within ‘VideoSourceNix’:
./VideoSource.h:80:22: note:    virtual nsresult VideoSource::Start(nsIDOMCanvasRenderingContext2D*)
In file included from MediaRecorder.h:61:0,
                 from MediaModule.cpp:37:
/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsStringAPI.h:1101:3: error: ‘char16_t’ was not declared in this scope
cc1plus: warnings being treated as errors
In file included from MediaRecorder.h:74:0,
                 from MediaModule.cpp:37:
./VideoSource.h:80:22: error: ‘virtual nsresult VideoSource::Start(nsIDOMCanvasRenderingContext2D*)’ was hidden
Linux/VideoSourceNix.h:53:14: error:   by ‘nsresult VideoSourceNix::Start(nsIOutputStream*, nsIDOMCanvasRenderingContext2D*)’
In file included from /home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsStringGlue.h:52:0,
                 from /home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsThreadUtils.h:47,
                 from VideoSource.h:48,
                 from VideoSource.cpp:37:
/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsStringAPI.h:1101:3: error: ‘char16_t’ was not declared in this scope
In file included from /home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsStringGlue.h:52:0,
                 from /home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsThreadUtils.h:47,
                 from ./VideoSource.h:48,
                 from Linux/VideoSourceNix.h:41,
                 from Linux/VideoSourceNix.cpp:37:
/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsStringAPI.h:1101:3: error: ‘char16_t’ was not declared in this scope
cc1plus: warnings being treated as errors
In file included from Linux/VideoSourceNix.cpp:37:0:
./VideoSource.h:80:22: error: ‘virtual nsresult VideoSource::Start(nsIDOMCanvasRenderingContext2D*)’ was hidden
Linux/VideoSourceNix.h:53:14: error:   by ‘nsresult VideoSourceNix::Start(nsIOutputStream*, nsIDOMCanvasRenderingContext2D*)’
In file included from /home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsStringGlue.h:52:0,
                 from /home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsThreadUtils.h:47,
                 from VideoSource.h:48,
                 from VideoSourceCanvas.h:40,
                 from VideoSourceCanvas.cpp:37:
/home/dunk/projects/rainbow/sdk/xulrunner-sdk//include/nsStringAPI.h:1101:3: error: ‘char16_t’ was not declared in this scope
make[1]: *** [libmediarecorder.so] Error 1
make[1]: Leaving directory`/data/dunk/projects/rainbow/components'
make: **\* [components/libmediarecorder.so] Error 2
dunk@atitude:~/projects/rainbow$

**Comment by daneoshiga** [comment]
I'm having the same issue!
same setup (natty + gcc 4.5.2)

looking at the bugzilla, found this related bug
https://bugzilla.mozilla.org/show_bug.cgi?id=559278 - wchar_t/char16_t problems when building against a SDK that was not built with the same flags
