### ISSUE TITLE
Ability to pass canvas ctx to Rainbow record

### ISSUE THREAD

**Issue by taboca** [mozilla/rainbow#2]
Hi, 
## Background: 

When Rainbow came out I was over excited because I thought it had to do with ability to record activity from canvas. Then, when testing 0.2 which works with Mac OS X 10.5 ( thanks ), I realized Rainbow records the video of the webcam. So here is what I think could be done moving forward: 
## Specification: 
- Rainbow itself would simply accept a reference to a canvas ctx as a "camera datasource"
- Camera is separated, So if you want to pass the camera ctx, it's a developer's step 

Impact: 

This way, we should enable a whole world of browser-based screencast applications ( for extensions ) and also greater creative use for web apps ( animations ) which will support open video efforts.

**Comment by taboca** [comment]
Added an example of a effect that has a blend of a webcam image with a a screencast - in my motivational post http://gecko.mgalli.com/the-canvas-pot-at-the-end-of-the-rainbow

**Comment by anantn** [comment]
Thanks for the feature request! We have added this capability in the 0.3 release of Rainbow, which went out today.
