### ISSUE TITLE
compile error with mozilla trunk

### ISSUE THREAD

**Issue by clarkbw** [mozilla/rainbow#3]
I keep running into this error when compiling against moz trunk.  This is against a new build of xulrunner.  I might be doing something wrong here but it seems there might be an error in PutImageData_explicit

Here's the error I'm seeing:

<pre>
make -C components
/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//bin/xpidl -m header -I/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//idl IMediaRecorder.idl
g++ -o MediaRecorder.o -DRAINBOW_Mac -c -pipe -Os -arch i386 -dynamiclib -mmacosx-version-min=10.5 -DMOZ_NO_MOZALLOC -fPIC -fno-rtti -fno-exceptions -fno-strict-aliasing -fno-common -fshort-wchar -fpascal-strings -pthread -Wall -Werror -Wconversion -Wpointer-arith -Woverloaded-virtual -Wsynth -Wno-ctor-dtor-privacy -Wno-non-virtual-dtor -Wcast-align -Wno-long-long -include xpcom-config.h -I. -IDarwin -I/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//include -I/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//include/system_wrappers -I/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//include/xpcom -I/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//include/string -I/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//include/content -I/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//include/dom -I/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//include/nspr -I/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//sdk/include -I../lib/Darwin_i386-gcc3/include MediaRecorder.cpp
In file included from Darwin/VideoSourceMac.h:42,
                 from MediaRecorder.h:63,
                 from MediaRecorder.cpp:37:
./VideoSource.h: In member function ‘virtual nsresult CanvasRenderer::Run()’:
./VideoSource.h:108: error: no matching function for call to ‘nsIDOMCanvasRenderingContext2D::PutImageData_explicit(int, int, PRUint32&, PRUint32&, unsigned char*, PRUint32&)’
/Users/clarkbw/src/mozilla/xul-runner-builds/objdir-mozilla/dist//include/nsIDOMCanvasRenderingContext2D.h:452: note: candidates are: virtual nsresult nsIDOMCanvasRenderingContext2D::PutImageData_explicit(PRInt32, PRInt32, PRUint32, PRUint32, PRUint8*, PRUint32, PRBool, PRInt32, PRInt32, PRInt32, PRInt32)
make[1]: *** [MediaRecorder.o] Error 1
make: *** [components/libmediarecorder.dylib] Error 2
</pre>

**Comment by clarkbw** [comment]
Tracked it down to this change in moz central
http://hg.mozilla.org/mozilla-central/rev/3cfa2011c831

This diff will fix it. I could do a pull request but my repo is a bit of a mess right now
https://gist.github.com/774948

**Comment by anantn** [comment]
Thanks for the patch! We released v0.3 today which should work on the latest Firefox betas.
