### ISSUE TITLE
use the gh-pages to provide examples that work after installing the add-on

### ISSUE THREAD

**Issue by clarkbw** [mozilla/rainbow#4]
I created a quick [gh-pages branch](https://github.com/clarkbw/rainbow/tree/gh-pages) such that I can have an [example page](http://clarkbw.github.com/rainbow/) that works with rainbow.  The only additional element that is required is that we add the equivalent of  http://clarkbw.github.com/rainbow/ ( something like http://mozilla.github.com/rainbow/ ) to the allowedDomains list.  If you add http://clarkbw.github.com/rainbow/ to your `extensions.rainbow.allowedDomains` the examples should work.

I did this to give people a quicker starting point for trying the add-on out.  Along with that I didn't include the streaming page since it requires an icecast server running on localhost; up to you.

Also I'm assuming that http://mozilla.github.com/rainbow/ would work if we created a gh-page branch for this; I haven't tested that.

**Comment by toolness** [comment]
Cool. Another option may be to have the rainbow repo issue a POST request to our server, at which point we pull and host the examples on a mozilla.com domain, if that's preferable.

**Comment by anantn** [comment]
Great idea! I merged in your fork, and voila: http://mozilla.github.com/rainbow/

I also added it to the 'default' preference for allowedDomains, but everyone who has already installed Rainbow will probably need to update the value manually.

Thanks!
