### ISSUE TITLE
Audio is out of sync

### ISSUE THREAD

**Issue by anantn** [mozilla/rainbow#5]
OGG files generated by Rainbow often have the audio and video components appear out of sync. The reason for this is that most webcams do not return frames at the requested rate (but the audio stream is mostly constant). We need to implement a more intelligent encoding method that analyzes the actual rate at which frames are received to produce synchronized video files.

**Comment by taboca** [comment]
Interesting. So maybe you could have a frame generator component that always makes sure to deliver the frame, aside from what you get from camera or canvas, and you always do the interpolation sort of thing. So when you do not get a frame, you serve the prior, til you get -- always keeping the last frame as the current. 

With this fix, we will be in amazing position to finally have videos created from Firefox. Canvas and Cam.

**Comment by anantn** [comment]
Theora is a fixed framerate format, so the suggested way to solve this is to set a nominal rate (15fps is reasonable) and then drop or duplicate frames to feed the encoder at that rate irrespective of when frames arrive from the webcam. This means we will have to:

a) Keep a copy of the last frame sent to the encoder around in case it needs to be duplicated.
b) Write timing information into the data pipe from both Audio and VideoSource so that MediaRecorder knows the times at which these frames arrived.
c) Add logic in MediaRecorder::Encode to keep track of timing information and drop or duplicate frames as necessary.
